services:
  
  # Service Frontend - React/Vite
  frontend:
    build: ./frontend
    container_name: react-hello2-frontend
  # Service Backend - NestJS/TypeScript
  backend:
    build: ./backend
    container_name: react-hello2-backend
    networks:
      - frontend_network
      - backend_network
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  # Service Database - MariaDB
  db:
    image: mariadb:latest
    container_name: react-hello2-db
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - backend_network

# Networks: isoler les communications
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

# Volumes: persistance de la base de donnÃ©es
volumes:
  db_data:
    driver: local
  
